# Generated by Django 3.1.2 on 2020-11-01 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='national_id',
            new_name='nati',
        ),
        migrations.CreateModel(
            name='business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('business_email', models.CharField(max_length=40)),
                ('neighbourhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.neighbourhood')),
                ('user_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neighbourhood.user')),
            ],
        ),
    ]
