# Generated by Django 3.1.2 on 2020-11-01 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0005_auto_20201101_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighbourhood',
            new_name='nhood',
        ),
    ]
