# Generated by Django 3.1.2 on 2020-11-01 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0006_auto_20201101_2133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nati',
            new_name='national_id',
        ),
    ]
